### ISSUE TITLE
api_genのクライアントサイドのKotlin対応

### ISSUE THREAD

**Issue by cs3238-tsuzu** [go-generalize/api_gen#129]
Web/Appどちらでも使えるライブラリを目指す

**Comment by cs3238-tsuzu** [comment]
Androidのみで良いなら簡単だがKotlin Nativeまで含めて対応することは可能なんだろうか？という点で調査(マルチプラットフォーム対応のライブラリがあるかどうか)する

**Comment by 54m** [comment]
Kotlinではなく、Flutter向けにDart対応でした
