### ISSUE TITLE
誤ったGroupが作成される。

### ISSUE THREAD

**Issue by sakura-rip** [go-generalize/api_gen#140]
環境: Windows10 Pro WSL Ubuntu 20.04.2 LTS,  go1.13.8 linux/amd64
ブランチ: v2

生成対象のディレクトリが
```
└─user
    │  register.go
    │  search.go
    └─_user_mid
            balance.go
            charge.go
            pay_history.go
            products.go
```
のようなとき、生成される/bootstrap_gen.goの中身が
![image](https://user-images.githubusercontent.com/56917703/108800029-5fc28700-75d5-11eb-8f29-c24c5a61fbb0.png)
上のようになり、
```
goimports exec error (/home/sakura/repos/manage-api/api_interfaces/bootstrap_gen.go): exit status 2
```
と表示される。

なお、register.go及びsearch.goを削除した場合は正常に生成される。
それぞれのファイルの中身は
![image](https://user-images.githubusercontent.com/56917703/108800273-03139c00-75d6-11eb-81a0-34cf9dbb53d2.png)
である。

**Comment by 54m** [comment]
:huyou:
