### ISSUE TITLE
SwaggerDocの不具合と要望

### ISSUE THREAD

**Issue by 54m** [go-generalize/api_gen#183]
# 不具合
```
// @Success 200 {object} types.GetArticleResponse
```
のtypesの部分がpackage名と同じじゃないとswagで生成できずエラーになる
SwagVersion: 1.7.0

# 要望
v1まであった、SummaryとDescription
```
// @Summary xxx
// @Description yyy
```
が消えてしまっている

## 方針
1. 構造体のコメントから抽出
2. 構造体に未使用フィールドを作り、タグに書き込んだものから抽出する
```
type Hoge struct {
    _ struct{} `type:"summary" contents:"xxx"`
    _ struct{} `type:"description" contents:"yyy"`
    ...
}
```
3. その他

いい感じに対応してもらえると助かります

**Comment by cs3238-tsuzu** [comment]
SummaryとDescriptionってAPI全体の方ですか?

**Comment by cs3238-tsuzu** [comment]
undocumentedなのでどこかに追加した方がいいですね

**Comment by cs3238-tsuzu** [comment]
`--parseDependency` を追加するとswagでエラーにならなくなる

**Comment by 54m** [comment]
> APIごとの方であれば `// @Summary` などのコメントをRequest/Responseの型定義の部分に書くことで生成されるものにも追加されるようになっています

@cs3238-tsuzu 
そのような処理がないように見えるのですが、手元にコード合ったりします？
![スクリーンショット 2021-05-28 15 48 14](https://user-images.githubusercontent.com/30588003/119941880-203c7a00-bfcc-11eb-8207-863dbd24b6e0.png)

**Comment by cs3238-tsuzu** [comment]
あれ！？生成がわに追加するコードのcommit漏れですかね?
PRだします

**Comment by cs3238-tsuzu** [comment]
PR出しました 🙇 
https://github.com/go-generalize/api_gen/pull/187

**Comment by 54m** [comment]
already merged
