### ISSUE TITLE
エラーの共通処理を挟み込める機構を追加

### ISSUE THREAD

**Issue by say-ya-sigma** [go-generalize/api_gen#202]
ミドルウエアをfetchが返ってからAPIClientがエラーを返すまでの間にも挟み込めるようにして、エラーに関する共通処理を仕込めるようになってほしい。

**Comment by moezakura** [comment]
https://emileber.github.io/axios-middleware/#/

**Comment by moezakura** [comment]
- GoのContextのようなものをInjectionして、beforeMiddleware, afterMiddlewareのそれぞれで扱えるようにする
- beforeMiddleware, afterMiddlewareでリクエストのBody、レスポンスのBodyをそれぞれ変更可能にする

**Comment by moezakura** [comment]
move https://github.com/go-generalize/api_gen/issues/322
