### ISSUE TITLE
error時のミドルウェアが欲しい

### ISSUE THREAD

**Issue by 54m** [go-generalize/api_gen#208]
現状apierrorををaddRoutes.add関数でc.JSONで握り潰してしまっていてechoのミドルウェアで拾えないのでapi_genでerror時のミドルウェアが必要な場面に遭遇した
echoのHTTPErrorHandler的な感じだと破壊的な変更にならないかも？

**Comment by tsuzu** [comment]
addRoutes.addでエラーを処理しないオプションを追加すると嬉しいですかね?

**Comment by 54m** [comment]
Slackで議論中
