### ISSUE TITLE
api_gen高速化プロジェクト

### ISSUE THREAD

**Issue by tsuzu** [go-generalize/api_gen#235]
実行時間が遅く生成に時間がかかり、CIに時間がかかったりなど生産性の低下につながっているので高速化する

**Comment by tsuzu** [comment]
#234 と #236 で　15sから4sになったのでかなり早くなってそう(PCの性能が十分なら

**Comment by tsuzu** [comment]
#237 でserver側も十分早くなったのでとりあえず問題なさそう?

**Comment by 54m** [comment]
これまだやる事あるので開きます

**Comment by tsuzu** [comment]
お、何やります?

**Comment by 54m** [comment]
GOMAXPROCSをデフォルトでは+1した方が良さそうかなと
あ、あとgo2goって最適化終わってたっけ

**Comment by tsuzu** [comment]
GOMAXPROCSはお作法的にいじっていいのかなぁ...と思っています
go2go自体には手を加えてないですがGo clientは他と同じ速度のはずです

**Comment by 54m** [comment]
まぁ実行時に指定してあげた方がいいか
OK, であればCloseしますね

**Comment by tsuzu** [comment]
まだできることもあると思いますがパフォーマンス的に問題になった時にまた取り組めば良いかなぁと思っています
