### ISSUE TITLE
TSのapi_client.tsでlintエラー

### ISSUE THREAD

**Issue by 54m** [go-generalize/api_gen#247]
![image](https://user-images.githubusercontent.com/30588003/147884202-b16fab27-eb2d-40c2-908f-bd6bc7f5e460.png)

v2.5.3 → v2.5.5

**Comment by tsuzu** [comment]
tsconfig.jsonに `"lib": [ "es2015" ],`が指定されていないのが原因っぽいですね

@54m
↑って指定されてますか?
このあたりは特に2.5.3と2.5.5で変更があった部分ではないと思うんですが

**Comment by 54m** [comment]
指定してないけど、前後で出るようになったから気になった
それを追加で指定しないと出るって認識でいいですかね

**Comment by tsuzu** [comment]
うーん、調べてもこれを指定しろ、ってことしか出てこないんですよねえ
とりあえずこれを指定して出なければそれで対処する、で良い気がします
