### ISSUE TITLE
dartクライアントコードがformatされてない

### ISSUE THREAD

**Issue by 54m** [go-generalize/api_gen#249]
![image](https://user-images.githubusercontent.com/30588003/148412719-f6395e99-8be1-4db3-b4e2-5365eef72329.png)

不要なimportが残っていたり、添付画像中のようにindentがtabだったりspaceだったりするので
analysis_optionsで除外するとはいえ、最低限のformatはかかった状態にしておきたいです
flutter formatしてみて出来るところまでで構いません！

**Comment by tsuzu** [comment]
できれば外部依存させずにdart formatを同梱できないかとちょっと試している

**Comment by tsuzu** [comment]
![Screen Shot 2022-01-07 at 17 35 48](https://user-images.githubusercontent.com/8574909/148515899-430b5640-96ea-4b30-acbd-0162c98330ea.png)

DartでPure Goで外部ツール依存をなくしてフォーマットできるようにしたがバイナリサイズが倍になってしまった・・・
