### ISSUE TITLE
あとなんかJsonのとこでconstにした方がいい的なWARNINGがIDEで出るんだよね

### ISSUE THREAD

**Issue by tsuzu** [go-generalize/api_gen#256]
あとなんかJsonのとこでconstにした方がいい的なWARNINGがIDEで出るんだよね

_Originally posted by @54m in https://github.com/go-generalize/api_gen/issues/251#issuecomment-1007328359_

調査 & 修正する

**Comment by tsuzu** [comment]
![2022-01-11 11 55のイメージ](https://user-images.githubusercontent.com/8574909/148873364-a0024b46-c8e4-4538-91ee-fc0fddd49c4e.jpg)

おそらくこれっぽい

**Comment by 54m** [comment]
あ、Android Studio入れてない？
色々出てくる

**Comment by tsuzu** [comment]
入れてないですね・・・

**Comment by tsuzu** [comment]
あーclientの方はいろいろ出てきますね

**Comment by 54m** [comment]
Android Studioで怒られてるところ言ってるだけなので今後は参考にして貰えると！
