### ISSUE TITLE
multipartデータを送れるようにしたい

### ISSUE THREAD

**Issue by 54m** [go-generalize/api_gen#260]

**Comment by tsuzu** [comment]
multipartって仕様として今までなんか策定してましたっけ
AutoBindを切ってるやつかな...?

**Comment by 54m** [comment]
今って、api_genで生成されたクライアントコードはjsonで送る想定で作られていると思います
AutoBindのやつはサーバー側なので送り手はapi_genの生成コードを使わずに自前で送らないと行けません(なのでラベルをクライアントにしています)

**Comment by tsuzu** [comment]
あーそうなんですけどまだクライアントって他でも全く実装されてないのでどうしようかなーと
多分Request/Responseどちらも型を全て無視する形になってしまいそうな気がしますね...

**Comment by tsuzu** [comment]
ちゃんとmultipartを実装するならAutoBind=falseは無くしてしまうべきな気がしますね(なんでも送れるのは仕様的に良くない)

**Comment by 54m** [comment]
それはそう

**Comment by tsuzu** [comment]
ちゃんとmultipart実装やるか...

**Comment by 54m** [comment]
サーバー側はAutoBindを消すくらいしか対応要らないと思うけどクライアントが大変かも..
あと、multipart使うには任意でBinder作ってもらわないといけないから一緒に生成してあげてもいいかも

**Comment by 54m** [comment]
@go-utils にあげとく

**Comment by tsuzu** [comment]
それはapi_genにあって良いのでは?

**Comment by tsuzu** [comment]
一般化できるならその方が良いのか?

**Comment by 54m** [comment]
2年くらい同じコード使い回してるレベルで変わらない内容だからこの際切り離していいかなって思ったw

**Comment by tsuzu** [comment]
あ、既にあるんですか
ならよさそう

**Comment by 54m** [comment]
サーバー側は一旦置いといて大丈夫です！
クライアント側の方が大変そうなので先に着手してもらえればとー

**Comment by tsuzu** [comment]
いや、multipart向けのタグ周りなどをそのBinderでやってるならそっちの仕様を把握したいんですよね

**Comment by 54m** [comment]
なるほど、少々お待ちを

**Comment by tsuzu** [comment]
なんならデフォルトのBinderにしてしまってよさそうですね

**Comment by 54m** [comment]
そうですね、echoのデフォは破壊してないただのミドルウェアです

**Comment by tsuzu** [comment]
![Screen Shot 2022-02-07 at 20 27 23](https://user-images.githubusercontent.com/8574909/152779697-c7f9500a-efbd-45c0-86d0-7d1e4782060a.png)

Dartはひとまず完成
