### ISSUE TITLE
Nullに対してStringにキャストしようとしている

### ISSUE THREAD

**Issue by 54m** [go-generalize/api_gen#265]
![image](https://user-images.githubusercontent.com/30588003/151716437-d3d5aca4-d302-427a-a043-2f5fd8f43b9f.png)

![image](https://user-images.githubusercontent.com/30588003/151716373-70fd10fd-a794-43f9-8020-308d405ad899.png)

**Comment by 54m** [comment]
![image](https://user-images.githubusercontent.com/30588003/151717948-121f41c5-d99f-40b3-ac01-b9a89ebca205.png)
こうすると落ちませんでしたが、nullになりませんでした(`deletedAt: 1970-01-01T00:00:00.000Z`)

**Comment by tsuzu** [comment]
確かにNullableConverterを噛ませなければいけないのは間違いなさそう
