### ISSUE TITLE
mapがnilの時に正しく動かない

### ISSUE THREAD

**Issue by 54m** [go-generalize/api_gen#280]
Goのmapはdartではnullableにした方が良さそう(Map<T, dynamic>?)
毎回初期化しないといけなくなる

**Comment by tsuzu** [comment]
実はわかってはいたけど対応に困って無視していた問題で，mapがnullableなのにnullableをつけ忘れてリリースしてここまできてしまったので今mapにnullableを付けると既存コードが壊れまくって困るんじゃないかというのを危惧しています(DartだけでなくTypeScriptなどでもつくようになるはず)
