### ISSUE TITLE
[Dart] マルチパート対応によるビルドエラー

### ISSUE THREAD

**Issue by 54m** [go-generalize/api_gen#284]
![image](https://user-images.githubusercontent.com/30588003/155663378-06d99da5-edd6-4078-b777-70c6d1dfeb14.png)

![image](https://user-images.githubusercontent.com/30588003/155662685-f3d05b20-1376-4f5b-9cc0-bc32380a3044.png)
![image](https://user-images.githubusercontent.com/30588003/155662822-f1523e32-2334-49bc-9279-c862f811e948.png)
MultipartFileConverterが見つけられてなさそう？
他にも色々と見つけられてなさそう

**Comment by tsuzu** [comment]
dart/flutterのバージョンなど教えてもらえますか?

**Comment by 54m** [comment]
@tsuzu 
```
$ flutter --version
Flutter 2.10.1 • channel stable
Framework • revision db747aa133 (3 weeks ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2
```
