### ISSUE TITLE
mockのjsonのTimeをいい感じにする。

### ISSUE THREAD

**Issue by moezakura** [go-generalize/api_gen#78]
毎回変わるのが流石に鬱陶しすぎるので、2006-01-02 15:04:05+09:00 にする。  
フォーマットが異質なのでRFC3339にする。

**Comment by 54m** [comment]
@moezakura 
RFC3339にすると、 `2006-01-02 15:04:05+09:00` ではなく `2006-01-02T15:04:05Z07:00` になる
