### ISSUE TITLE
client_generatorの生成するClientで参照できないクライアントが生成されることがある

### ISSUE THREAD

**Issue by moezakura** [go-generalize/api_gen#82]
client_generatorで何もControllerがない階層を1つ挟むと正常に参照できないクライアントが生まれる。  
具体的には以下の構成だとAPIClient classから辿れないApiClientが生成される。

```text
/
├── api
│   ├── products
│   │   ├── get_hogehoge_controller_gen.go
│   │   ├── mock_routes_gen.go
│   │   ├── hogehoge.go
│   │   └── routes_gen.go
├── bootstrap_gen.go
```

**Comment by cs3238-tsuzu** [comment]
あれ、生成できていませんか・・・？
![スクリーンショット 2021-02-03 14 59 41](https://user-images.githubusercontent.com/8574909/106705049-83c32600-6630-11eb-8033-70047090451b.png)
![スクリーンショット 2021-02-03 14 59 23](https://user-images.githubusercontent.com/8574909/106705039-7dcd4500-6630-11eb-9ac3-a401e233de0b.png)
![スクリーンショット 2021-02-03 14 59 38](https://user-images.githubusercontent.com/8574909/106705048-832a8f80-6630-11eb-8150-feb8e99ace8f.png)

**Comment by 54m** [comment]
invalid
